#!/usr/bin/env bash

export AQPKGP_SYSTEM=/var/lib/aquaproj-aqua
export AQPKG_USER=$HOME/.local/share/aquaproj-aqua

source /etc/aqpkg.conf

if [ -f ~/.config/aqpkg.conf ]; then
    source ~/.config/apkg.conf
else
    touch ~/.config/apkg.conf
fi

if (( $EUID = 0 )); then
    echo "use -s flag for system wide package management"
    exit 1
fi

while getopts ":s:" option; do
  case $option in
    *)
      case $1 in
      init)
        curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v2.2.0/aqua-installer | bash
        ;;
      aqua-init)
        echo "Stopping..."
        ;;
      *)
        echo ""
        ;;
        esac
          ;;
    s)
      case $1 in
      init)
        sudo mkdir /var/lib/aquaproj-aqua
        sudo ln -s /root/.local/share/aquaproj-aqua /var/lib/aquaproj-aqua
        sudo curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v2.2.0/aqua-installer | bash
        ;;
      aqua-init)
        echo "Stopping..."
        ;;
      *)
        echo ""
        ;;
        esac
      ;;
    *)
      # code to execute when an unknown flag is provided
      ;;
  esac
done



