#!/usr/bin/env bash

source /etc/aqpkg.conf

if [ -f ~/.config/aqpkg.conf ]; then
    source ~/.config/apkg.conf
else
    touch ~/.config/apkg.conf
fi
source ~/.config/aqpkg.conf

if (( $EUID = 0 )); then
    echo "use -s flag for system wide package management"
    exit 1
fi

while getopts ":s:" option; do
  case $option in
    *)
      case $1 in
      init)
        curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v2.2.0/aqua-installer | bash
        ;;
      aqua-init)
        echo "Stopping..."
        ;;
      *)
        echo ""
        ;;
    esac
      ;;
    s)
      # code to execute when flag2 is provided
      ;;
    *)
      # code to execute when an unknown flag is provided
      ;;
  esac
done



